### ISSUE TITLE
external Radius

### ISSUE THREAD

**Issue by idnovic** [lunatech-labs/lunatech-unifi-wifi#1]
Hello does it work with an external radius server or only with the internal from unifi?

If it works with an external radius, the radius server needs to be set up as external inside the unifi control software?

Thank you!

**Comment by wjglerum** [comment]
Hi, thanks for reaching out to us!

This application is mainly developed for our use-case and not meant to be generic at the moment. It generates a radius account on the internal RADIUS server on the Unifi USG based on your login with Google G-Suite. 

I don't think it will work with an external RADIUS server as the Unifi Controller can't manage an external RADIUS server as far as I know. I would interact with your external RADIUS server or the underlying datasource directly.
